### ISSUE TITLE
Don't build on ios

### ISSUE THREAD

**Issue by emersonart** [4sh/squashed-cordova-plugin-googlemaps#2]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.9.0 "Google Maps SDK for iOS"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.14 "AppVersion"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-file 7.0.0 "File"
cordova-plugin-firebasex 16.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation-permission-status 1.0.0 "Cordova Plugin Geolocation Permission Status"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-wkwebview-engine 1.2.2 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
"'Cordova/CDVCommandDelegateImpl.h' file not found " when building to run on the simulator or when archiving

**Expected behavior:**
When running the build in xcode, generating the app and running in the simulator

**Screen capture or video record:**
![Captura de Tela 2023-09-01 às 10 28 55](https://github.com/4sh/squashed-cordova-plugin-googlemaps/assets/5253941/b24d7e42-1f61-43fd-8c16-4b6d8caccbbf)

**Related code, data or error log (please format your code or data):**

```
cordova-ios: ^7.0.0
cordova: 12.0.0 (cordova-lib@12.0.1)
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by dmolinet-nexus** [comment]
Same here, any updates?

**Comment by mobilespot** [comment]
me too

**Comment by atullvtiger** [comment]
This issue is because of [Cordova iOS 7+](https://cordova.apache.org/announcements/2023/07/10/cordova-ios-7.0.0.html). CDVCommandDelegateImpl.h has been removed from public API

**Comment by mcastets** [comment]
Hi guys, a new version (`2.7.3`) has been released.
